'use client'
import { Providers } from "./GlobalRedux/provider";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Providers>
        <body className="bg-blue-400" >{children}</body>
      </Providers>

    </html>
  )
}
